apiVersion: v1
kind: Secret
metadata:
  name: dynakube-secret
  namespace: dynatrace
type: Opaque
stringData:
  apiToken: "REPLACE_WITH_YOUR_DT_API_TOKEN"
  dataIngestToken: "REPLACE_WITH_YOUR_DT_PAAS_TOKEN"
