apiVersion: v1
kind: ConfigMap
metadata:
  name: tier4-config
  namespace: loan-app
data:
  TIER5_URL: "http://tier5-service.loan-app.svc.cluster.local:5000"
  APPROVAL_THRESHOLD: "60"
  REJECTION_THRESHOLD: "40"
