apiVersion: v1
kind: Secret
metadata:
  name: tier4-secret
  namespace: loan-app
type: Opaque
stringData:
  DT_ENV_URL: "https://YOUR_ENVIRONMENT_ID.live.dynatrace.com"
  DT_API_TOKEN: "dt0c01.YOUR_API_TOKEN_HERE"  # Requires bizevents.ingest scope
